### ISSUE TITLE
RunTimeError: CuDNN error: CUDNN_STATUS_SUCCESS when train the model

### ISSUE THREAD

**Issue by whungt** [NYUMedML/DeepEHR#2]
I'm trying to train the model with trainModel.py, following the command in ReadMe. But I've encountered the error in the title.

I'm on win7 machine with anaconda. GPU: RTX 2070.
My virtual env configuration:
python 3.6.8
cudatoolkit 9.0
cudnn 7.3.1
pytorch 0.4.1
torchvision 0.2.1

This error occurs at the very beginning of the running. There's no concern of run out of memory or related problems.

Someone help me on this? What's your configuration to run this successfully?
Thanks in advance.

**Comment by jingsliu** [comment]
Can you attach the error log please?
We used Linux machines so I'm not sure if the os is the issue

**Comment by whungt** [comment]
@jingsliu 
![Capture](https://user-images.githubusercontent.com/17772419/57167844-e258d180-6dc4-11e9-9fa1-815884095b73.JPG)

**Comment by jingsliu** [comment]
Yeah looks like a purely CuDNN issue. I need to double check later but I believe we used pytorch 0.4.1 and CuDNN >= 8.

**Comment by whungt** [comment]
Well...It seems that there is no cuDNN 8 yet. The latest one is cuDNN 7.5 for CUDA 10.1

![Capture2](https://user-images.githubusercontent.com/17772419/57169405-11267600-6dcc-11e9-9c6f-556473388318.JPG)

**Comment by whungt** [comment]
OK. It turns out that there seems to be some incompatible bugs between cuda/torch and some RTX GPUs.
I got the problem fixed by installing cuda92 in my virtual env:
conda install pytorch cuda92 -c pytorch
So now my configurations are:
win7 with RTX 2070, cuda 10.1.105
anaconda virtual env:
python 3.7.3
cudatoolkit 10.0.130
cudnn 7.3.1
cuda92 1.0
pytorch 1.1.0

Also, when I train the model, I need to add an exception line in enc_model.py:
Change line 773 to be:
```
try:
        train_loss += loss.data[0]
except IndexError:
        train_loss+=loss.data.item()
```
Similarly, change line 822 to be:
```
try:
        test_loss += (self.criterion(output, Disease)).data[0]
except IndexError:
        test_loss += (self.criterion(output, Disease)).data.item()
```
